server:
  port: 8040

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  level:
    com.tulingxueyuan.order.feign: debug
feign:
  client:
    config:
      product-service:
#        连接超时时间
        connectTimeout: 5000
#        服务处理超时时间
        readTimeout: 3000
        requestInterceptors[0]:
          com.tulingxueyuan.order.intceptor.CustomFeignInterceptor
