server:
  port: 8040

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  level:
    com.tulingxueyuan.order.feign: debug
